version: 0.2

phases:
  install:
    run-as: root
    on-failure: ABORT
    commands:
      - echo Updating latest updates in Linux...
      - yum update -y
      - docker --version
      - echo "Using IAM Role credentials for AWS access"
      - aws sts get-caller-identity
      - aws configure get region
      - echo AWS credentials and region are configured

  pre_build:
    run-as: root
    on-failure: ABORT
    commands:
      - echo Entered the pre_build phase...
      - aws ecr get-login-password --region $aws_region | docker login --username AWS --password-stdin $container_registry
      - echo ECR Docker Login successful...

  build:
    run-as: root
    on-failure: ABORT
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo CodeBuild build number: $CODEBUILD_BUILD_NUMBER
      - pwd
      - ls -la
      - echo Cloning application repository...
      - git clone https://github.com/Theja2709/aws-rds-java.git javaweb-repo
      - cd javaweb-repo
      - docker build -t $container_registry/$ecr_repo:$env_image_tag$CODEBUILD_BUILD_NUMBER .
      - docker images
      - docker push $container_registry/$ecr_repo:$env_image_tag$CODEBUILD_BUILD_NUMBER
      - echo Build completed successfully

  post_build:
    run-as: root
    on-failure: ABORT
    commands:
      - echo Updating GIT Repository...
      - git clone -b master https://github.com/Theja2709/aws-rds-java.git /root/aws-rds-java
      - cd $git_path
      - sed -i "s|$container_registry/$ecr_repo:$env_image_tag$(($CODEBUILD_BUILD_NUMBER-1))|$container_registry/$ecr_repo:$env_image_tag$CODEBUILD_BUILD_NUMBER|g" $deployment_file
      - git add .
      - git commit -am "Updating deployment YAML file"
      - git push origin main
      - echo Finished pushing to GIT Repository.

artifacts:
  files:
    - "**/*"
