version: 0.2

phases:
  install:
    commands:
      - echo "Starting installation phase..."
      - set -e # Exit immediately if any command fails
      - if ! command -v docker &> /dev/null; then
          echo "Docker not found. Installing Docker...";
          yum update -y;
          yum install -y docker;
          service docker start;
        else
          echo "Docker is already installed.";
        fi
      - docker --version
      - echo "Installation phase completed."

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Cloning the GitHub repository..."
      - git clone $GITHUB_REPO_URL
      - echo "Navigating to the application directory..."
      - cd aws-rds-java
      - echo "Pre-build phase completed."

  build:
    commands:
      - echo "Build phase started..."
      - echo "Building the application using Maven..."
      - cd aws-rds-java # Ensure the directory is correct
      - mvn clean install
      - echo "Creating a Docker image..."
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo "Build phase completed."

  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo "Post-build phase completed."

artifacts:
  files:
    - '**/*' # Include all files
  base-directory: target/LoginWebApp # Adjust based on your Maven target output

env:
  variables:
    AWS_REGION: "us-east-1" # Change to your AWS region
    AWS_ACCOUNT_ID: "061039798183" # Change to your AWS Account ID
    IMAGE_REPO_NAME: "javaweb-repo" # Change to your ECR repository name
    GITHUB_REPO_URL: "https://github.com/Theja2709/aws-rds-java.git" # Your GitHub repo URL
