version: 0.2

phases:
  install:
    commands:
      - echo "Starting installation phase..."
      - yum update -y
      - yum install -y docker
      - echo "Installation completed."

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - echo "configure aws cli"
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region $AWS_REGION
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Cloning the GitHub repository..."
      - git clone https://github.com/Theja2709/aws-rds-java.git
      - echo "Navigating to the application directory..."
      - cd aws-rds-java
      - echo "Pre-build phase completed."

  build:
    commands:
      - echo "Build phase started..."
      - echo "Building the application using Maven..."
      - mvn clean install
      - echo "Creating a Docker image..."
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo "Build phase completed."

  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo "Post-build phase completed."

artifacts:
  files:
    - '**/*'
