version: 0.2

phases:
  install:
    commands:
      - echo "Starting installation phase..."
      - yum update -y
      - yum install -y docker
      - docker --version
      - echo "Installation completed."

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - echo "Logging in to Amazon ECR..."
      - aws sts get-caller-identity
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 061039798183.dkr.ecr.us-east-1.amazonaws.com
      - echo "Cloning the GitHub repository..."
      - git clone https://github.com/Theja2709/aws-rds-java.git
      - echo "Navigating to the application directory..."
      - cd aws-rds-java
      - echo "Pre-build phase completed."

  build:
    commands:
      - echo "Build phase started..."
      - echo "Building the application using Maven..."
      - mvn clean install
      - echo "Creating a Docker image..."
      - docker build -t javaweb-repo .
      - docker tag javaweb-repo:latest 061039798183.dkr.ecr.us-east-1.amazonaws.com/javaweb-repo:latest
      - docker push 061039798183.dkr.ecr.us-east-1.amazonaws.com/javaweb-repo:latest
      - echo "Build phase completed."

  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo "Post-build phase completed."

artifacts:
  files:
    - '**/*' # All files (optional, adjust as needed)
  base-directory: target/LoginWebApp # Target directory for application output

env:
  variables:
    AWS_REGION: "us-east-1" # Change to your AWS region
    AWS_ACCOUNT_ID: "061039798183" # Change to your AWS Account ID
    IMAGE_REPO_NAME: "javaweb-repo" # Change to your ECR repository name
    GITHUB_REPO_URL: "https://github.com/Theja2709/aws-rds-java.git" # Replace with your GitHub repo URL
